source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
xcodeproj 'Anypic.xcodeproj'


workspace 'Anypic'

pod 'Parse'
pod 'ParseFacebookUtils'
pod 'ParseCrashReporting'
pod 'ParseUI'
pod 'Facebook-iOS-SDK'

link_with 'Parse', 'ParseFacebookUtils', 'ParseCrashReporting', 'ParseUI', 'Facebook-iOS-SDK'